---
- name: Add ruby ppa
  apt_repository: repo='ppa:brightbox/ruby-ng'
  register: add_ruby_ppa

- name: Update package list for ruby
  apt: update_cache=yes
  when: add_ruby_ppa is changed

- name: Install ruby
  become: yes
  apt:
    name:
      - ruby2.3
      - ruby2.3-dev
  ignore_errors: '{{ ansible_check_mode }}'
