---

- name: Update the apt cache
  when: shared_drive_enabled|bool
  apt:
    update_cache: yes
    cache_valid_time: 7200

- name: Install NFS packages
  become: yes
  when: shared_drive_enabled|bool
  apt:
    name:
      - nfs-kernel-server
      - portmap
  tags:
    - nfs

- name: ensure nfs service is running
  when: shared_drive_enabled|bool
  service:
    name: nfs-kernel-server
    state: started
  tags:
    - nfs

- name: Create group with same GID
  become: yes
  group:
    name: "{{ shared_dir_groupname }}"
    state: present
    gid: "{{ shared_dir_gid }}"
  tags:
    - nfs
    - shared_files

- name: Add cchq to nfs group
  user:
    name: "{{ cchq_user }}"
    groups: "{{ shared_dir_groupname }}"
    append: yes
  tags:
    - nfs
    - shared_files
