---

ansigenome_info:
  galaxy_url: 'https://galaxy.ansible.com/debops-contrib/etckeeper'
  github_url: 'https://github.com/ypid/ansible-contrib-etckeeper'
  git_branch: 'master'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Robin Schneider'
      email: 'ypid@riseup.net'
      github: 'ypid'

  synopsis: |
    `debops-contrib.etckeeper` will install [etckeeper][] which puts `/etc`
    under version control. To do this it hooks into the package management and
    from now on automatically commit changes to a local git repository under
    `/etc/.git`.

    This makes it easy to see which changes are applied on a specific host and
    quickly revert them, if something breaks.

    ### Credits
    This role was influenced by [groover.etckeeper](https://github.com/silpion/ansible-etckeeper)
    but has been rewritten from scratch to make it suitable for the DebOps project.

    [etckeeper]: https://github.com/joeyh/etckeeper
