---

etckeeper__supported_vcs:
  - git
  - hg
  - bzr
  - darcs


# .. envvar:: etckeeper__vcs_command_to_package_mapping:
#
# Predefined VCS to package mapping (only if the two differ).
etckeeper__vcs_command_to_package_mapping:
  hg: 'mercurial'


# .. envvar:: etckeeper__highlevel_to_lowlevel_package_manager_mapping
#
# Predefined high-level to low-level package manager mapping.
etckeeper__highlevel_to_lowlevel_package_manager_mapping:
  apt: 'dpkg'
  yum: 'rpm'
  dnf: 'rpm'
  zypper: 'rpm'
  # 'pacman-g2': ''
