---
- name: Start postgres
  become: yes
  action: service name=postgresql args="{{ postgresql_version }}" state=started

- name: Restart postgres
  become: yes
  action: service name=postgresql args="{{ postgresql_version }}" state=restarted

- name: Reload postgres
  become: yes
  action: service name=postgresql args="{{ postgresql_version }}" state=reloaded

- name: reload systemd
  become: yes
  systemd:
    daemon_reload: yes
