---
- name: Add rabbitmq official apt key
  become: true
  apt_key: id=0x0A9AF2115F4687BD29803A206B73A36E6026DFCA keyserver=hkps.pool.sks-keyservers.net state=present

- name: Add rabbitmq official apt repository
  become: true
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Install rabbitmq
  become: true
  apt: name=rabbitmq-server state=present
  notify:
  - restart rabbitmq

- name: Place config file
  template:
    src: "rabbitmq.config.j2"
    dest: "/etc/rabbitmq/rabbitmq.config"
    group: root
    owner: rabbitmq
    mode: 0644

- name: Make sure RabbitMQ service is started before running config tasks
  become: yes
  service: name=rabbitmq-server state=started

- include: config-cluster.yml
  when: rabbitmq_create_cluster|bool

- include: config.yml
  when: not rabbitmq_create_cluster or ( ansible_fqdn == hostvars[rabbitmq_cluster_master]['ansible_fqdn'] )

- name: Enable and start RabbitMQ service
  become: yes
  service: name=rabbitmq-server state=started
  tags: after-reboot

- include: join-cluster.yml
  when: (rabbitmq_create_cluster | bool) and ( ansible_fqdn != hostvars[rabbitmq_cluster_master]['ansible_fqdn'] )

- include: ha-policy.yml
  when: (rabbitmq_create_cluster| bool ) and ( ansible_fqdn == hostvars[rabbitmq_cluster_master]['ansible_fqdn'] )
