---
- name: Add rabbitmq official apt repository
  become: true
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Install rabbitmq
  become: true
  apt: pkg=rabbitmq-server state=installed force=yes
  notify:
  - restart rabbitmq

- name: Place config file
  template:
    src: "rabbitmq.config.j2"
    dest: "/etc/rabbitmq/rabbitmq.config"
    group: root
    owner: rabbitmq
    mode: 0644

- include: config-cluster.yml
  when: rabbitmq_create_cluster

- include: config.yml
  when: not rabbitmq_create_cluster or ( ansible_fqdn == hostvars[rabbitmq_cluster_master]['ansible_fqdn'] )

- name: Enable and start RabbitMQ service
  become: yes
  service: name=rabbitmq-server state=started
  tags: after-reboot

- include: join-cluster.yml
  when: (rabbitmq_create_cluster == true) and ( ansible_fqdn != hostvars[rabbitmq_cluster_master]['ansible_fqdn'] )
