postgresql_version: '9.6'
postgresql_cluster_name: 'main'
postgresql_port: 5432
postgresql_ssl_enabled: False
postgresql_dir_original_path: /var/lib/postgresql
postgresql_dir_path: "{{ encrypted_root }}/postgresql"
postgresql_process_path: "{{ '/var/run/postgresql' if ansible_distribution_version == '18.04' else postgresql_dir_path }}"
postgresql_backup_dir: "{{ encrypted_root }}/backups/postgresql"
postgresql_home: "{{ postgresql_dir_path }}/{{ postgresql_version }}/main"
postgresql_config_home: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_pid_file: "{{ postgresql_process_path }}/{{ postgresql_version }}-main.pid"
postgres_install_dir: "/usr/lib/postgresql/{{ postgresql_version }}"
postgresql_log_directory: "{{ postgresql_home }}/pg_log"
postgresql_recovery_conf: "{{ postgresql_home }}/recovery.conf"
postgresql_num_logs_to_keep: 20
pgstandby_wal_keep_segments: 8
postgresql_wal_keep_segments: 8

allow_dump_from_pgstandby: "{{ postgres_users.get('netvault') != None }}"

# defaults should match the postgresql defaults
postgresql_max_connections: 20
postgresql_work_mem: '8MB'
postgresql_shared_buffers: '1024MB'
postgresql_max_stack_depth: '2MB'
postgresql_effective_cache_size: '128MB'
postgresql_max_standby_delay: 0  # 0 means don't set in postgresql.conf (leaving default value)
postgresql_maintenance_work_mem: '64MB'
postgresql_checkpoint_completion_target: '0.5'
postgresql_wal_buffers: '-1'
postgresql_default_statistics_target: '100'
postgresql_max_wal_size: '256MB'
postgresql_slow_log_threshold: 300
postgresql_random_page_cost: 4.0

allow_direct_postgresql_access: no
allow_direct_citusdb_access: no

postgresql_apt_repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename}}-pgdg main"
postgresql_apt_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
postgresql_binary: "postgresql-{{ postgresql_version }}"

postgresql_shared_preload_libraries:
 - 'pg_stat_statements'
