- name: Create aws config directory for {{ s3_user }}
  become: yes
  file:
    path: '{{ s3_user_home_dir }}/.aws'
    owner: "{{ s3_user }}"
    group: "{{ s3_user }}"
    mode: 0700
    state: directory


- name: Set up ~/.aws/credentials for {{ s3_user }}
  become: yes
  template:
    src: "aws_credentials.j2"
    dest: "{{ s3_user_home_dir }}/.aws/credentials"
    group: "{{ s3_user }}"
    owner: "{{ s3_user }}"
    mode: 0700
    backup: yes

- name: Set up ~/.aws/config for {{ s3_user }}
  become: yes
  file:
    path: "{{ s3_user_home_dir }}/.aws/config"
    state: absent
