---

- include: setup_cluster.yml
  when: is_redis_cluster|bool

- name: start the redis service
  service: name="{{ redis_service_name }}" state=started enabled=yes
  tags: after-reboot

- name: redis monit config
  become: yes
  template:
    src: "monit.redis.j2"
    dest: "/etc/monit/conf.d/redis"
    group: root
    owner: root
    mode: 0640
  notify: reload monit
  tags: monit

- meta: flush_handlers

- monit:
    name: redis
    state: monitored
  tags: monit
  ignore_errors: "{{ ansible_check_mode }}"
  register: result
  until: not result.failed or 'process not presently configured with monit' not in result.msg
  retries: 5
  delay: 20
