---
- name: Install redis gem
  command: 'gem install redis -v 3.3.3' # not the latest, because https://github.com/antirez/redis/issues/4272
  become: yes

- name: Add cluster config
  become: yes
  lineinfile:
    dest: /etc/redis/{{ redis_port }}.conf
    line: '{{ item.key }} {{ item.value }}'
  with_dict: "{{ cluster_config }}"
  tags: redis_config

- name: Start redis service
  service: name="{{ redis_service_name }}" state=restarted enabled=yes
