---
- import_playbook: host_group_aliases.yml

- name: CitusDB Machine Setup
  hosts:
    - citusdb_worker
    - citusdb_master
  become: true
  roles:
    - {role: ecryptfs, tags: 'ecryptfs'}

- name: CitusDB
  hosts: 
    - citusdb_worker
    - citusdb_master
  become: true
  roles:
    - {role: citusdb, tags: 'citusdb'}

- name: pgbouncer
  hosts: citusdb_master
  become: true
  roles:
    - {role: pgbouncer, tags: 'pgbouncer'}


# Disables transparent huge pages (THP)
- name: Disable THP
  become: true
  hosts:
    - citusdb_worker
    - citusdb_master
  tags: 'kernel_tuning'
  roles:
    - role: thp
