---
- name: Check for already mounted encrypted tmp drive
  shell: grep '{{ encrypted_tmp }} ecryptfs' /etc/mtab
  register: mtab_contents
  failed_when: false
  changed_when: false
  check_mode: no

- name: Unmount tmp drive
  become: yes
  shell: "umount {{ encrypted_tmp }}"
  when: encrypted_tmp in mtab_contents.stdout

- name: Remove cron job
  become: yes
  cron:
    name: "Purge files in {{ encrypted_tmp }}"
    cron_file: purge_tmp_files
    user: root
    state: absent
